<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <Description>DataAnnotations attributes for Attest: validate a national identification number, tax identification number or VAT code on a model property.</Description>
    <PackageId>Attest.DataAnnotations</PackageId>
  </PropertyGroup>



  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Annotations" Version="4.7.0" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\Attest\Attest.csproj" />
  </ItemGroup>


</Project>
