<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <Description>DataAnnotations to validate VAT codes, social security numbers or tin numbers.</Description>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <PackageTags>Data Annotations, VAT, SSN, Id, Social Security Number, TIN, Countries Validator</PackageTags>
    <PackageProjectUrl>https://github.com/Egoushka/attest</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Egoushka/attest</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Version>1.0.0</Version>
    <PackageId>Attest.DataAnnotations</PackageId>
  </PropertyGroup>



  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Annotations" Version="4.7.0" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\Attest\Attest.csproj" />
  </ItemGroup>


</Project>
